### ISSUE TITLE
Dialect precedence

### ISSUE THREAD

**Issue by dtrunk90** [Antibrumm/thymeleaf-extras-with-dialect#8]
The with dialect should be processed after the standard dialect.
This is causing an exception for example as the with attributes seems to be processed before `th:each`/`th:unless`:
```
<p th:unless="${#maps.isEmpty(myMap)}" th:each="row : ${myMap}" with:i="${i} + ${rowStat.index}" />
```

Exception is: `org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'index' cannot be found on null`

**Comment by Antibrumm** [comment]
With the version 3.0.1 I aligned the dialect and the processor precedence with the built-in `StandardWithTagProcessor`. https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/standard/processor/StandardWithTagProcessor.java

This had to be done so the behaviour is exactly the same as in the standard way.

You can always move the declaration into a `th:block` either before or after to achieve different results.

**Comment by dtrunk90** [comment]
Fixed
